ALTER TABLE Posts
DROP CONSTRAINT fk_replyID, fk_threadID, fk_userID

DROP TABLE IF EXISTS Threads
CREATE TABLE Threads(
	threadID int NOT NULL AUTO_INCREMENT PRIMARY KEY,
	title varchar(255) NOT NULL,
);
DROP TABLE IF EXISTS Users
CREATE TABLE Users (
	userID int identity PRIMARY KEY,
	username varchar(255) NOT NULL,
	password varchar(255) NOT NULL,
);
DROP TABLE IF EXISTS Posts
CREATE TABLE Posts (
	postID int identity PRIMARY KEY,
	threadID int NOT NULL,
	userID int NOT NULL,
	replyID int DEFAULT NULL,
	body varchar(255) NOT NULL,
	time DATETIME DEFAULT CURRENT_TIMESTAMP,
);

ALTER TABLE POSTS
ADD CONSTRAINT fk_threadID
FOREIGN KEY (threadID) REFERENCES Threads(threadID)

ALTER TABLE POSTS
ADD CONSTRAINT fk_userID
FOREIGN KEY (userID) REFERENCES Users(userID)

ALTER TABLE POSTS
ADD CONSTRAINT fk_replyID
FOREIGN KEY (replyID) REFERENCES Posts(postID)


